ci: add changeset check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,7 @@ jobs:
       contents: read
       pull-requests: read
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - name: Lint commit messages
@@ -24,11 +24,36 @@ jobs:
           failOnWarnings: true
           helpURL: https://github.com/SaulMoro/ngrx-rtk-query/blob/main/.github/CONTRIBUTING.md#-commit-message-guidelines
 
+  check-changeset:
+    runs-on: ubuntu-latest
+    name: Check Changeset
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: ./.github/composite-actions/install
+      - name: Check and Validate Changes in /packages/ngrx-rtk-query
+        run: |
+          git fetch origin main:main
+          changes=$(git diff --name-only main...${{ github.sha }} | grep '^packages/ngrx-rtk-query/' || true)
+          if [[ -n "$changes" ]]; then
+            echo "Changes detected in /packages/ngrx-rtk-query: $changes"
+            pnpm changeset status --since origin/main
+            exit_status=$?
+            if [[ $exit_status -eq 0 ]]; then
+              echo "Changeset validation succeeded."
+            else
+              echo "Changeset validation failed."
+            fi
+          else
+            echo "No changes detected in /packages/ngrx-rtk-query"
+          fi
+
   lint:
     runs-on: ubuntu-latest
     name: Lint
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: ./.github/composite-actions/install
@@ -38,17 +63,17 @@ jobs:
   format:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: ./.github/composite-actions/install
       - name: Validate
-        run: pnpm exec nx-cloud record -- nx format:check
+        run: pnpm exec nx-cloud record -- pnpm format:check
 
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: ./.github/composite-actions/install
@@ -60,7 +85,7 @@ jobs:
     needs:
       - build
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: ./.github/composite-actions/install
@@ -72,7 +97,7 @@ jobs:
     needs:
       - build
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: ./.github/composite-actions/install
